version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - inbound_api_key
    command: bash -c "pip install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/news_api
    ports:
      - "8000:8000"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - inbound_api_key
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - .:/news_api
