# Generated by Django 2.1.4 on 2018-12-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='source',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='top_news.Author'),
            preserve_default=False,
        ),
    ]
