# Generated by Django 2.1.4 on 2018-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_news', '0002_auto_20181217_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uid',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
