# Generated by Django 2.1.4 on 2018-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_news', '0003_auto_20181217_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uid',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
